---
  extends:
    - standard
  parser: babel-eslint
  env:
    browser: true
    node: true
  rules:
    max-len:
      - error
      - code: 120
        tabWidth: 2
    array-bracket-spacing:
      - error
      - always
    object-curly-spacing:
      - error
      - always
    computed-property-spacing:
      - error
      - always
