---
  image: node:latest

  variables:
    NODE_ENV: production

  before_script:
    - npm install

  build:
    stage: build
    artifacts:
      expire_in: 1d
      paths:
        - out
    script:
      - ./enovel GRAVITY_TALES 1144 chaotic-sword-god csg
      - ./enovel WUXIAWORLD 2548 martial-god-asura mga
      - ./enovel WUXIAWORLD 1503 martial-world mw

  stages:
    - build
